adminUser: admin
adminPassword: admin  # Change this to a secure password

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'Spring Boot Dashboards'
        orgId: 1
        folder: 'Spring Boot'
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards

extraConfigmapMounts:
  - name: spring-boot-dashboard
    mountPath: /var/lib/grafana/dashboards
    configMap: spring-boot-dashboard
    readOnly: true
