apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-deployment
spec:
  template:
    spec:
      containers:
      - name: discovery-service
        image: aksdemoQNUmml.azurecr.io/discovery-service:latest
