# This file contains the essential configs for the ingress controller helm chart

verbosityLevel: 3
appgw:
  subscriptionId: 0cfe2870-d256-4119-b0a3-16293ac11bdc
  resourceGroup: 1-912eadbf-playground-sandbox
  name: application-gateway
  shared: false

armAuth:
  type: servicePrincipal
  secretJSON: ewogICJjbGllbnRJZCI6ICIwNTU5NTU3Yy05OTZmLTRlMzMtYTBkYy0xOTE0ODA3YWFmOGEiLAogICJjbGllbnRTZWNyZXQiOiAiangtOFF+b1dtX0dCfk5hai1vb3hrVS5fZU1VSGdEWDVvT0oyQWJEUSIsCiAgInN1YnNjcmlwdGlvbklkIjogIjBjZmUyODcwLWQyNTYtNDExOS1iMGEzLTE2MjkzYWMxMWJkYyIsCiAgInRlbmFudElkIjogIjg0ZjFlNGVhLTg1NTQtNDNlMS04NzA5LWYwYjg1ODllYTExOCIsCiAgImFjdGl2ZURpcmVjdG9yeUVuZHBvaW50VXJsIjogImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSIsCiAgInJlc291cmNlTWFuYWdlckVuZHBvaW50VXJsIjogImh0dHBzOi8vbWFuYWdlbWVudC5henVyZS5jb20vIiwKICAiYWN0aXZlRGlyZWN0b3J5R3JhcGhSZXNvdXJjZUlkIjogImh0dHBzOi8vZ3JhcGgud2luZG93cy5uZXQvIiwKICAic3FsTWFuYWdlbWVudEVuZHBvaW50VXJsIjogImh0dHBzOi8vbWFuYWdlbWVudC5jb3JlLndpbmRvd3MubmV0Ojg0NDMvIiwKICAiZ2FsbGVyeUVuZHBvaW50VXJsIjogImh0dHBzOi8vZ2FsbGVyeS5henVyZS5jb20vIiwKICAibWFuYWdlbWVudEVuZHBvaW50VXJsIjogImh0dHBzOi8vbWFuYWdlbWVudC5jb3JlLndpbmRvd3MubmV0LyIKfQ==
rbac:
  enabled: true

aksClusterConfiguration:
  apiServerAddress: aks-dns-ktmudthy.privatelink.southcentralus.azmk8s.io

