compact: true
quiet: true
skip-download: false
download-external-modules: true
directory:
  - ./
skip-check:
  - CKV_AZURE_164
  - CKV_AZURE_237
  - CKV_AZURE_167
  - CKV_AZURE_139
  - CKV_AZURE_233
  - CKV_AZURE_165
  - CKV_AZURE_117
  - CKV_AZURE_170
  - CKV_AZURE_4
  - CKV_AZURE_116
  - CKV2_AZURE_2
  - CKV2_AZURE_12
  - CKV2_AZURE_27
  - CKV_AZURE_23
  - CKV_AZURE_120