apiVersion: v1
kind: Service
metadata:
  name: employee-performance-service
spec:
  selector:
    app: employee-performance-deployment
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
