apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: employee-performance-service-pdb
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: employee-performance-deployment
